/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.helloworld
dialect "mvel"
 
import fr.gouv.education.sirhen.ct.moteurregles.transverse.util.DateUtil;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.AgentFait;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.ContratFait;

rule "RAN_C_400"
    @CodeONP(RAN_C_400)
	@NoyauONP(16.10.00)
	@Evenements(T1592) 
	@Populations(P0199)
	@Bloquante
	@Libelle("La date de fin prévisionnelle ou la date de fin réelle du contrat doit être obligatoirement saisie.")
    when
        ContratFait(typeContrat == "TC01", (dateFinPrevisionelleLienJuridique != null || dateFinReelLienJuridique != null)) 
    then
end