package fr.edu.sirhen
dialect "mvel"
 
import fr.gouv.education.sirhen.ct.moteurregles.transverse.util.DateUtil;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.AgentFait;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.ContratFait;

rule "RAN_C_001"
    @CodeONP(RAN_C_001)
	@NoyauONP(16.00.00)
	@Evenements(T1592) 
	@Populations(P0199)
	@Bloquante
	@Libelle("La date de début du contrat est postèrieure ou égale à la date d'entrée dans la FPE ou dans la carrière militaire.")
    when
        $agent : AgentFait(dateEntreeFonctionPublique != null) 
        $contratFait : ContratFait(dateDebutLienJuridique != null, eval(DateUtil.afterIncludePrecisionJour(dateDebutLienJuridique,$agent.dateEntreeFonctionPublique)))
         
    then
end