/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.helloworld
dialect "mvel"
 
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.AgentFait;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.ContratFait;

rule "RAN_C_005"
    @CodeONP(RAN_C_005)
	@NoyauONP(16.00.00)
	@Evenements(T1592) 
	@Populations(P0199)
	@Bloquante
	@Libelle("La date de fin prévisionnelle du contrat est postèrieure ou égale à la date de début du contrat")
	@Commentaire("On ajoute la contrainte dateDebutLienJuridique!= null, ce qui n'a pas d'impact fonctionnel du fait de RAN_C_927")
   when
	   ContratFait((dateFinPrevisionelleLienJuridique != null && dateFinReelLienJuridique == null),dateDebutLienJuridique != null , eval(DateUtil.afterIncludePrecisionJour(dateFinPrevisionelleLienJuridique, dateDebutLienJuridique)))
   then
end