package org.drools.examples.helloworld
dialect "mvel"

import fr.gouv.education.sirhen.ct.moteurregles.transverse.util.DateUtil;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.AgentFait;
import fr.gouv.education.sirhen.gin.gestiondescontratsdesnontitulaires.fait.ContratFait;

rule "RAN_C_024"
    @CodeONP(RAN_C_024)
	@NoyauONP(16.00.00)
	@Evenements(T1592) 
	@Populations(P0199)
	@Libelle("La date de fin prévisionnelle du contrat est inférieure à la date limite de départ à la retraite.")
    when
     	$contrat : ContratFait(dateFinPrevisionelleLienJuridique != null, dateFinReelLienJuridique == null)
    	AgentFait(eval(DateUtil.afterIncludePrecisionJour(dateLimiteRetraite, $contrat.dateFinPrevisionelleLienJuridique)))   
    then

end